### ISSUE TITLE
Code review - PR #32

### ISSUE THREAD

**Issue by EmCousin** [EmCousin/pkp#33]
This Pull Request #32 seems to do a bunch of things, but is poorly documented.
Your task is to review the code, add comments upon the lines you think require clarification.

### TODO : 
- [x] Checkout the branch related to this PR
- [x] Make sure it works
- [x] If it doesn't work, comment on the PR what corrections need to be done
- [x] Comment with how you think the code could be written better

Once you're done, you can either : 
- Request changes, detailing what changes you would like to be implemented
- Comment
- Approve
